### ISSUE TITLE
System.ObjectDisposedException when using the MediaTranscoder class

### ISSUE THREAD

**Issue by lhak** [microsoft/CsWinRT#584]
I use the MediaTranscoder class to convert a stream of bitmaps to a video file. This works fine when using .net core 3.1, but fails when using .net 5. After supplying a few frames, a System.ObjectDisposedException is thrown in System.Private.CoreLib.dll. The stacktrace is shown below:

```
at media_transcoder_test.MainWindow.StartMediaTranscodeSession(String outputFile, UInt32 videoWidth, UInt32 videoHeight, UInt32 framerate) in media_transcoder_test\MainWindow.xaml.cs:line 128 
at media_transcoder_test.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) in media_transcoder_test\MainWindow.xaml.cs:line 35
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at media_transcoder_test.App.Main()
```

 I have attached a repro project that generates up to 200 (empty) frames and tries to generate a mpeg-4 video out of them. When started using vscode it fails after around 100 frames on my machine. It also fails when started without debugging. Interestingly, this repro project finishes on my machine when running under the visual studio debugger so I suspect some kind of timing related issue.
[media_transcoder_test.zip](https://github.com/microsoft/CsWinRT/files/5540869/media_transcoder_test.zip)

**Comment by Scottj1s** [comment]
Looks like this has been fixed.  No longer repros with:
  <ItemGroup>
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.19041.10" />
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.19041.10" />
  </ItemGroup>

**Comment by lhak** [comment]
Unfortunately, I can still reproduce the problem even with those lines added to the project file.

**Comment by Scottj1s** [comment]
@lhak investigating again

**Comment by pjmagee** [comment]
Hi, I am also receiving this exception but did not get this exception when running on .NET Core 3.1 with the NuGet Package `<PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.19041.1" />`. 

I tried to make a small reproducible bit of C# code and I thought maybe I could handle it myself or see where in my code it was now breaking, but it seems to be an external call as I suspected. 

Does anything look particularly wrong with the following very simple code that I am using to take screenshots? The real application needs to take a screenshot each second and then converts it to a `SoftwareBitmap` for OCR usage.

https://gist.github.com/pjmagee/d74ba9c0e3f5b9bbdb732ca05c9f7c4b

**Comment by Scottj1s** [comment]
@pjmagee - do you have a complete repro project?  My attempt to wrap your source file with a console csproj with TargetFramework = net5.0-windows10.0.19041.0 and a nuget reference to System.Drawing.Common results in:

Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
An exception of type 'System.Runtime.InteropServices.COMException' occurred in System.Private.CoreLib.dll but was not handled in user code
The image is unrecognized. (0x88982F60)

**Comment by Scottj1s** [comment]
@pjmagee - never mind, my target window was minimized, causing the BitBlt to fail.  I have the repro with ObjectDisposedException - thx.

**Comment by pjmagee** [comment]
@Scottj1s  I'm not very good at understanding the abstractions and complexities with how WinRT works with C# but I'd be interested to at least read through an area of the code which may be causing this. More curiosity than being able to submit a bug fix myself.

**Comment by Scottj1s** [comment]
@pjmagee - thanks to your repro, I think I've root caused and have a fix - the team is evaluating.  In short, the .NET 5 runtime may occasionally hand out a disposed RCW for a given COM pointer, via [ComWrappers.GetOrCreateObjectForComInstance](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.comwrappers.getorcreateobjectforcominstance?view=net-5.0).  This happens most often with recycled COM pointers that are temporarily wrapped for callbacks (e.g., async handlers).  The solution is to resurrect the disposed wrapper and reregister it with the GC.  

Fix, using reflection (temporarily):
https://github.com/microsoft/CsWinRT/compare/ujjwalchadha/fix-media-transcoder-error?expand=1#diff-61ead3a3c21696d411a1071c0e16e284e38c804c6fde4f68ddd2da7301e110d3

**Comment by Scottj1s** [comment]
see also:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1251438

**Comment by Scottj1s** [comment]
**Workaround:** if the identity of the disposed RCW can be determined, then the app can stash a reference to it to prevent premature disposing.

**Comment by lhak** [comment]
I upgraded to cswinrt 1.1.1, but I can still reproduce this issue.

**Comment by lhak** [comment]
Can this bug be reopened? I can still reproduce it after upgrading to 1.1.3.

**Comment by pjmagee** [comment]
This is holding me back from moving to .NET 5 from NET Core 3.1

**Comment by manodasanW** [comment]
@lhak @pjmagee Are both your repros still the same from above and do you have a stack for your current failure?  When you capture the stack, can you in Exception settings configure to break on _System.ObjectDisposedException_ and provide the stack from when that is hit.

Can you both also confirm what version of WinRT.Runtime is loaded in the process?

I feel like given the use of async calls in your repro, you are hitting a variant of this issue which was recently fixed by #682  which the stack should help confirm.  The CsWinRT 1.1.3 update had part of the fix (the changes in WinRT.Runtime), but the other part still needs to ship in an updated Windows SDK projection which we will update for 1.1.4 and ingested in an upcoming .NET SDK servicing update.  Typically we update both at the same time, but 1.1.3 was shipped early to fix a regression in the CsWinRT package.

**Comment by lhak** [comment]
Yes, the repro project is still the same, I just added the cswinrt 1.1.3 nuget package and can confirm that WinRT.Runtime has this version. The stacktrace is the following:

```
	WinRT.Runtime.dll!WinRT.IObjectReference.ThrowIfDisposed()	
 	WinRT.Runtime.dll!ABI.WinRT.Interop.IAgileReference.WinRT.Interop.IAgileReference.Resolve(System.Guid riid)	
 	WinRT.Runtime.dll!WinRT.AgileReference.Get()	
 	Microsoft.Windows.SDK.NET.dll!ABI.Windows.Foundation.AsyncOperationWithProgressCompletedHandler<uint, uint>.NativeDelegateWrapper.Invoke(Windows.Foundation.IAsyncOperationWithProgress<uint, uint> asyncInfo, Windows.Foundation.AsyncStatus asyncStatus)	
 	Microsoft.Windows.SDK.NET.dll!System.Threading.Tasks.TaskToAsyncInfoAdapter<System.__Canon, System.__Canon, uint, uint>.OnCompletedInvoker(Windows.Foundation.AsyncStatus status)	
 	Microsoft.Windows.SDK.NET.dll!System.Threading.Tasks.TaskToAsyncInfoAdapter<Windows.Foundation.AsyncOperationWithProgressCompletedHandler<uint, uint>, Windows.Foundation.AsyncOperationProgressHandler<uint, uint>, uint, uint>.Completed.set(Windows.Foundation.AsyncOperationWithProgressCompletedHandler<uint, uint> value)	
 	Microsoft.Windows.SDK.NET.dll!ABI.Windows.Foundation.IAsyncOperationWithProgress<uint, uint>.Vftbl.Do_Abi_put_Completed_2(System.IntPtr thisPtr, System.IntPtr handler)	


```

**Comment by manodasanW** [comment]
Thanks @lhak .  The stack helps confirm your issue is the agile reference variant of this issue which was fixed by #682 .  We plan on shipping a Windows SDK projection update for 1.1.4 which should then be included in the .NET SDK servicing update that follows it.

**Comment by pjmagee** [comment]
Maybe unrelated, but in the original reproduce code I provided. There was a block:

https://gist.github.com/pjmagee/d74ba9c0e3f5b9bbdb732ca05c9f7c4b#file-reproduce-cs-L61

Is that block safe?

**Comment by manodasanW** [comment]
@pjmagee Was there something you were specifically concerned about in that block?

**Comment by pjmagee** [comment]
> @pjmagee Was there something you were specifically concerned about in that block?

Im not too versed in the Graphics API. I am releasing the device contexts, but im not sure if thats enough or if the way its being used is robust? I just dont want this not cleaning up correctly which may contribute to any kind of leaking.
